# Generated by Django 6.0 on 2025-12-19 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('PENDING', 'Pending Review'), ('APPROVED', 'Approved by Admin'), ('CONFIRMED', 'Confirmed (Manager Assigned)'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('REJECTED', 'Rejected'), ('MAINTENANCE', 'Maintenance')], default='Draft', max_length=50),
        ),
    ]
